[tool.pylint]
max-line-length = 100
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
]
good-names = ["i", "j", "k", "ex", "Run", "id", "db"]
ignore = ["CVS", ".git", "*.pyc", "*.egg-info", "*.eggs", "*.yml", "cdk.out", ".venv", "node_modules"]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
python_files = ["test_*.py"]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
] 