name: GPS Tracker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install pylint bandit
        
    - name: Run linting
      run: |
        pylint --rcfile=pyproject.toml lib/ tests/ app.py
        
    - name: Run security scan
      run: |
        bandit -r .
        
    - name: Run infrastructure tests
      run: |
        pytest tests/test_dynamodb_stack.py -v
        